version: '3'

services:
  consul-server-1:
    image: consul:1.10
    container_name: consul-server-1
    volumes:
      - ./servers/server01:/etc/consul.d
    networks:
      - consul
    command: 'agent -bootstrap-expect=3 -config-dir=/etc/consul.d'
  consul-server-2:
    image: consul:1.10
    container_name: consul-server-2
    volumes:
      - ./servers/server02:/etc/consul.d
    networks:
      - consul
    command: 'agent -bootstrap-expect=3 -config-dir=/etc/consul.d'
  consul-server-3:
    image: consul:1.10
    container_name: consul-server-3
    volumes:
      - ./servers/server03:/etc/consul.d
    networks:
      - consul
    command: 'agent -bootstrap-expect=3 -config-dir=/etc/consul.d'
  consul-client-1:
    image: consul:1.10
    container_name: consul-client-1
    volumes:
      - ./clients/consul01:/etc/consul.d
    networks:
      - consul
    command: 'agent -config-dir=/etc/consul.d'
  consul-client-2:
    image: consul:1.10
    container_name: consul-client-2
    volumes:
      - ./clients/consul02:/etc/consul.d
    networks:
      - consul
    command: 'agent -config-dir=/etc/consul.d'
networks:
  consul:
    driver: bridge
